version: 2

sources:
  - name: raw_video_game
    schema: public_raw_video_game
    tables:
      - name: games
        freshness:
          warn_after:
            count: 7
            period: day
          error_after:
            count: 30
            period: day
        loaded_at_field: CAST("Post Date" AS TIMESTAMP)

      - name: vgsales
        freshness:
          warn_after:
            count: 7
            period: day
          error_after:
            count: 30
            period: day
        loaded_at_field: CAST("Post Date" AS TIMESTAMP)